[
    {
        "name": "Finland / Estonia",
        "url": "finland-estonia",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "finland.jpg",
        "bannerimageurl": "finland_banner.jpg",
        "term": ["semester", "springbreak"],
        "region": "europe",
        "deadline": "February 1, 2022",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "March 2022",
        "themes": ["Best Practices in Global Education"],
        "futuredates": ["Spring Break '22"],
        "teachabroad": false
    },
    {
        "name": "Mexico",
        "url": "mexico",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "ecuador.jpg",
        "bannerimageurl": "ecuador_banner.jpg",
        "term": ["semester", "springbreak"],
        "region": "centralamerica",
        "deadline": "February 1, 2022",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "March 2022",
        "themes": [],
        "futuredates": ["Spring Break '22, Spring Break '24"],
        "teachabroad": false
    },
    {
        "name": "France",
        "url": "france",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "france.jpg",
        "bannerimageurl": "france_banner.jpg",
        "term": ["semester", "summer"],
        "region": "europe",
        "deadline": "April 1, 2021",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "Summer 2021",
        "themes": ["Teach Abroad", "Best Practices in Global Education", "Historical Depth and Context"],
        "futuredates": ["Summer '21", "Summer '22", "Summer '23", "Summer '24"],
        "teachabroad": true
    },
    {
        "name": "Spain",
        "url": "spain",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "spain.jpg",
        "bannerimageurl": "spain_banner.jpg",
        "term": ["springbreak"],
        "region": "europe",
        "deadline": "February 1, 2022",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "March 2022",
        "themes": ["Citizenship in a Global Era", "Best Practices in Global Education", "Historical Depth and Context"],
        "futuredates": ["Spring Break '22", "Spring Break '24"],
        "teachabroad": false
    },
    {
        "name": "Spain Semester",
        "url": "spain-semester",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "spain.jpg",
        "bannerimageurl": "spain_banner.jpg",
        "term": ["semester"],
        "region": "europe",
        "deadline": "April 1, 2021",
        "credits": "N/A",
        "cost": "$13,500",
        "dates": "Fall 2021",
        "themes": ["Citizenship in a Global Era", "Best Practices in Global Education", "Historical Depth and Context"],
        "futuredates": ["Fall '22", "Fall '23", "Fall '24"],
        "teachabroad": false
    },
    {
        "name": "Italy",
        "url": "italy",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "italy.jpg",
        "bannerimageurl": "italy_banner.jpg",
        "term": ["springbreak"],
        "region": "europe",
        "deadline": "February 1, 2021",
        "credits": "N/A",
        "cost": "$2000",
        "dates": "March 2021",
        "themes": ["Best Practices in Global Education", "Historical Depth and Context"],
        "futuredates": ["Spring Break '21", "Spring Break '22", "Spring Break '23"],
        "teachabroad": false
    },
    {
        "name": "Italy Semester",
        "url": "italy-semester",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "italy.jpg",
        "bannerimageurl": "italy_banner.jpg",
        "term": ["semester"],
        "region": "europe",
        "deadline": "April 1, 2021",
        "credits": "N/A",
        "cost": "$13,500",
        "dates": "Fall 2021",
        "themes": ["Best Practices in Global Education", "Historical Depth and Context"],
        "futuredates": ["Fall '21", "Fall '22", "Fall '23", "Fall '24"],
        "teachabroad": false
    },
    {
        "name": "Ireland Semester",
        "url": "ireland-semester",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "ireland.jpg",
        "bannerimageurl": "ireland_banner.jpg",
        "term": ["semester"],
        "region": "europe",
        "deadline": "April 1, 2023",
        "credits": "N/A",
        "cost": "$13,500",
        "dates": "Fall Semester 2021",
        "themes": [],
        "futuredates": ["Semester '21", "Semester '22", "Semester '23", "Semester '24"],
        "teachabroad": false
    },
    {
        "name": "Ireland",
        "url": "ireland",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "ireland.jpg",
        "bannerimageurl": "ireland_banner.jpg",
        "term": ["springbreak"],
        "region": "europe",
        "deadline": "February 1, 2023",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "March 2023",
        "themes": [],
        "futuredates": ["Spring Break '23"],
        "teachabroad": false
    },
    {
        "name": "Costa Rica Semester",
        "url": "costarica-semester",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "costarica.jpg",
        "bannerimageurl": "costarica_banner.jpg",
        "term": ["semester"],
        "region": "centralamerica",
        "deadline": "April 1, 2021",
        "credits": "N/A",
        "cost": "$13,500",
        "dates": "Fall Semester '21",
        "themes": ["Preparing Schools for a Changing Environment"],
        "futuredates": ["Semester '21", "Semester '22", "Semester '23", "Semester '24"],
        "teachabroad": false
    },
    {
        "name": "Costa Rica",
        "url": "costarica",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "costarica.jpg",
        "bannerimageurl": "costarica_banner.jpg",
        "term": ["springbreak"],
        "region": "centralamerica",
        "deadline": "February 1, 2023",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "March 2023",
        "themes": ["Preparing Schools for a Changing Environment"],
        "futuredates": ["Spring Break '23", "Spring Break '25"],
        "teachabroad": false
    },
    {
        "name": "Japan / Taiwan",
        "url": "japan",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "japan.jpg",
        "bannerimageurl": "japan_banner.jpg",
        "term": ["summer"],
        "region": "asia",
        "deadline": "April 1, 2021",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "Summer 2021",
        "themes": ["Best Practices in Global Education", "Historical Depth and Context"],
        "futuredates": ["Summer '21", "Summer '23"],
        "teachabroad": false
    },
    {
        "name": "India",
        "url": "india",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "india.jpg",
        "bannerimageurl": "india_banner.jpg",
        "term": ["summer"],
        "region": "asia",
        "deadline": "April 1, 2021",
        "credits": "3-4 hours",
        "cost": "$2500",
        "dates": "Summer 2021",
        "themes": ["Resilience in Schools to (Re)Build Communities"],
        "futuredates": ["Summer '21", "Summer '23"],
        "teachabroad": false
    },
    {
        "name": "Ecuador",
        "url": "ecuador",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "ecuador.jpg",
        "bannerimageurl": "ecuador_banner.jpg",
        "term": ["summer"],
        "region": "southamerica",
        "deadline": "April 1, 2021",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "Summer 2021",
        "themes": ["Preparing Schools for a Changing Environment"],
        "futuredates": ["Summer '21", "Summer '23"],
        "teachabroad": false
    },
    {
        "name": "Singapore",
        "url": "singapore",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "singapore.jpg",
        "bannerimageurl": "singapore_banner.jpg",
        "term": ["summer"],
        "region": "asia",
        "deadline": "April 1, 2021",
        "credits": "3-4 hours",
        "cost": "$1500",
        "dates": "Summer 2021",
        "themes": ["Teach Abroad", "Best Practices in Global Education"],
        "futuredates": ["Summer '21", "Summer '22", "Summer '23", "Summer '24"],
        "teachabroad": true
    },
    {
        "name": "Tanzania",
        "url": "tanzania",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "tanzania.jpg",
        "bannerimageurl": "tanzania_banner.jpg",
        "term": ["summer"],
        "region": "africa",
        "deadline": "April 1, 2021",
        "credits": "3-4 hours",
        "cost": "$3000",
        "dates": "Summer 2021",
        "themes": ["Resilience in Schools to (Re)Build Communities"],
        "futuredates": ["Summer '21", "Summer '23"],
        "teachabroad": false
    },
    {
        "name": "Indonesia",
        "url": "indonesia",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "indonesia.jpg",
        "bannerimageurl": "indonesia_banner.jpg",
        "term": ["summer"],
        "region": "asia",
        "deadline": "April 1, 2022",
        "credits": "3-4 hours",
        "cost": "$2500",
        "dates": "Summer 2022",
        "themes": ["Citizenship in a Global Era", "Resilience in Schools to (Re)Build Communities"],
        "futuredates": ["Summer '22", "Summer '24"],
        "teachabroad": false
    },
    {
        "name": "Namibia",
        "url": "namibia",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "namibia.jpg",
        "bannerimageurl": "namibia_banner.jpg",
        "term": ["summer"],
        "region": "africa",
        "deadline": "April 1, 2022",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "Summer 2022",
        "themes": ["Resilience in Schools to (Re)Build Communities"],
        "futuredates": ["Summer '22", "Summer '24"],
        "teachabroad": false
    },
    {
        "name": "Greece",
        "url": "greece",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "greece.jpg",
        "bannerimageurl": "greece_banner.jpg",
        "term": ["summer"],
        "region": "europe",
        "deadline": "April 1, 2022",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "Summer 2022",
        "themes": ["Citizenship in a Global Era", "Resilience in Schools to (Re)Build Communities", "Historical Depth and Context"],
        "futuredates": ["Summer '22", "Summer '24"],
        "teachabroad": false
    },
    {
        "name": "Jordan",
        "url": "jordan",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "jordan.jpg",
        "bannerimageurl": "jordan.jpg",
        "term": ["summer"],
        "region": "asia",
        "deadline": "December 20, 2020",
        "credits": "3-4 hours",
        "cost": "$500",
        "dates": "Summer 2021",
        "themes": ["Citizenship in a Global Era", "Resilience in Schools to (Re)Build Communities", "Historical Depth and Context", "Teach Abroad"],
        "futuredates": ["Summer '21"],
        "teachabroad": true
    },
    {
        "name": "Hong Kong / Macau",
        "url": "hongkong-macau",
        "learnmore": "https://forms.illinois.edu/sec/949661",
        "imageurl": "hongkong-macau.jpg",
        "bannerimageurl": "hongkong-macau_banner.jpg",
        "term": ["winter"],
        "region": "asia",
        "deadline": "October 28, 2021",
        "credits": "3-4 hours",
        "cost": "$2000",
        "dates": "January 2022",
        "themes": ["Citizenship in a Global Era", "Resilience in Schools to (Re)Build Communities", "Historical Depth and Context"],
        "futuredates": ["Winter '22", "Winter '23", "Winter '24"],
        "teachabroad": false
    }
]